# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-31 08:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.IntegerField()),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trains.Station')),
                ('tid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trains.Train')),
            ],
        ),
    ]
